spring.application.name=multas-biblioteca-api
server.port=8080

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:multas_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Pasarela de pago activa: pagosudes | wompi
app.pagos.proveedor=pagosudes
